name: diaryapp
description: "A new Flutter project."

# This line prevents accidental publishing to pub.dev.
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

# Environment settings
environment:
  sdk: '>=3.5.3 <4.0.0'

# Dependencies required for the app to work
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.0
  intl: ^0.19.0
  table_calendar: ^3.0.0
  http_parser: ^4.0.2
  collection: 1.18.0
  github_sign_in_plus: ^0.0.2

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8

# Dev dependencies used for testing and linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter specific configurations
flutter:
  uses-material-design: true

  # Asset management
  assets:
    - assets/background.jpg
    - assets/first_page.jpg
